version: 2
updates:
  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Europe/Paris
    cooldown:
      default-days: 10
    assignees:
      - Scille/ops-code-owners
    directory: /
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Europe/Paris
    cooldown:
      default-days: 10
    open-pull-requests-limit: 5
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      pre-commit:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:20"
      timezone: Europe/Paris
    cooldown:
      default-days: 10
    open-pull-requests-limit: 15
    rebase-strategy: auto
    pull-request-branch-name:
      separator: "-"
    groups:
      dev-prettier:
        dependency-type: development
        patterns:
          - prettier*
      dev-deps:
        dependency-type: development
        patterns:
          - "*"
      prod-deps:
        dependency-type: production
        patterns:
          - "*"
